build:
  no_build: true
environments:
  default:
    workflows:
      - name: "dbx-demo-job"
        spark_python_task:
          python_file: "file://dbx-demo-job.py"
      - name: "dbx-notebook-demo-job"
        notebook_task:
            notebook_path: "file://notebook2.py"
